"use server";

import { render } from "@react-email/render";
import {
  and,
  asc,
  eq,
  exists,
  gt,
  inArray,
  notExists,
  sql,
} from "drizzle-orm";
import { z } from "zod";

import type { BaseProfile } from "@/app/api/users/definitions";
import FestivalActivationEmailTemplate from "@/app/emails/festival-activation";
import RegistrationInvitationEmailTemplate from "@/app/emails/registration-invitation";
import { getFestivalSectorAllowedCategories } from "@/app/lib/festival_sectors/helpers";
import type { FestivalWithDates } from "@/app/lib/festivals/definitions";
import {
  INVITATION_KINDS,
  type InvitationAudienceResult,
  type InvitationBatchResult,
  type InvitationKind,
  type InvitationPageFailure,
} from "@/app/lib/festivals/invitation-definitions";
import {
  INVITATION_MAX_PAGES_PER_CALL,
  INVITATION_PAGE_SIZE,
  invitationIdempotencyKey,
  isDeliverableEmail,
  partitionRecipients,
} from "@/app/lib/festivals/invitation-helpers";
import { requireAdminOrFestivalAdmin } from "@/app/lib/users/helpers";
import { sendBatchEmails } from "@/app/vendors/resend";
import { db } from "@/db";
import {
  festivals,
  festivalSectors,
  profileSubcategories,
  tickets,
  users,
  visitors,
} from "@/db/schema";

const VISITOR_FROM = "Equipo Glitter <equipo@productoraglitter.com>";
const VISITOR_REPLY_TO = "visitantes@productoraglitter.com";
const PARTICIPANT_FROM = "Productora Glitter <eventos@productoraglitter.com>";

const FestivalIdSchema = z.number().int().positive();
const KindSchema = z.enum(INVITATION_KINDS);
const BatchInputSchema = z.object({
  festivalId: FestivalIdSchema,
  kind: KindSchema,
  // Generated by the browser once per send run; scopes the idempotency keys.
  runId: z.uuid(),
  cursor: z.number().int().nonnegative(),
  maxPages: z
    .number()
    .int()
    .min(1)
    .max(INVITATION_MAX_PAGES_PER_CALL)
    .default(INVITATION_MAX_PAGES_PER_CALL),
});

type Recipient = { id: number; email: string };
type VisitorRecipient = Recipient & { firstName: string | null };

async function loadFestival(festivalId: number) {
  const festival = await db.query.festivals.findFirst({
    where: eq(festivals.id, festivalId),
    with: { festivalDates: true },
  });
  if (!festival) return null;
  // The email reads the first and last date; the relation is unordered.
  festival.festivalDates.sort(
    (a, b) => a.startDate.getTime() - b.startDate.getTime(),
  );
  return festival;
}

/**
 * Why `kind` cannot be sent for this festival right now, or null when it can.
 * Checked on every page, not only once: acreditación can close mid-run, and
 * every email links to a page that would then say registration is closed.
 */
function sendBlocker(festival: FestivalWithDates, kind: InvitationKind) {
  if (festival.status !== "active") {
    return "Activa el festival antes de enviar invitaciones.";
  }
  if (kind === "visitor_registration") {
    if (!festival.publicRegistration) {
      return "Abre la acreditación antes de invitar a los visitantes.";
    }
    if (festival.festivalDates.length === 0) {
      return "Agrega las fechas del festival antes de invitar a los visitantes.";
    }
  }
  return null;
}

/**
 * The participant categories a festival has stands for: who the activation
 * mail is for. Leaves out the retired `new_artist` and `none`, which no
 * participant can reserve under.
 */
async function festivalCategories(festivalId: number) {
  const sectors = await db.query.festivalSectors.findMany({
    columns: { id: true },
    with: { stands: { columns: { standCategory: true } } },
    where: eq(festivalSectors.festivalId, festivalId),
  });
  return [
    ...new Set(
      sectors.flatMap((sector) => getFestivalSectorAllowedCategories(sector)),
    ),
  ].filter((category) => category !== "none");
}

/**
 * Who can act on the activation mail. Its button opens the festival's terms
 * page, which turns away a profile without subcategories, so mailing one
 * would only send them to an error.
 */
function invitableParticipant(categories: BaseProfile["category"][]) {
  return and(
    eq(users.status, "verified"),
    inArray(users.category, categories),
    exists(
      db
        .select({ one: sql`1` })
        .from(profileSubcategories)
        .where(eq(profileSubcategories.profileId, users.id)),
    ),
  );
}

function hasTicketForFestival(festivalId: number) {
  return db
    .select({ one: sql`1` })
    .from(tickets)
    .where(
      and(eq(tickets.visitorId, visitors.id), eq(tickets.festivalId, festivalId)),
    );
}

async function visitorPage(festivalId: number, cursor: number) {
  return db
    .select({
      id: visitors.id,
      email: visitors.email,
      firstName: visitors.firstName,
    })
    .from(visitors)
    .where(
      and(
        gt(visitors.id, cursor),
        notExists(hasTicketForFestival(festivalId)),
      ),
    )
    .orderBy(asc(visitors.id))
    .limit(INVITATION_PAGE_SIZE);
}

async function participantPage(
  categories: BaseProfile["category"][],
  cursor: number,
) {
  if (categories.length === 0) return [];
  return db
    .select()
    .from(users)
    .where(and(gt(users.id, cursor), invitableParticipant(categories)))
    .orderBy(asc(users.id))
    .limit(INVITATION_PAGE_SIZE);
}

async function buildVisitorEmails(
  recipients: VisitorRecipient[],
  festival: FestivalWithDates,
) {
  return Promise.all(
    recipients.map(async (visitor) => ({
      from: VISITOR_FROM,
      to: [visitor.email],
      replyTo: VISITOR_REPLY_TO,
      subject: `Pre-registro abierto: ${festival.name}`,
      html: await render(
        RegistrationInvitationEmailTemplate({
          festival,
          visitorName: visitor.firstName,
        }),
      ),
      tags: [
        { name: "category", value: "festival_registration_invitation" },
        { name: "festival_id", value: String(festival.id) },
      ],
    })),
  );
}

async function buildParticipantEmails(
  recipients: BaseProfile[],
  festival: FestivalWithDates,
) {
  return Promise.all(
    recipients.map(async (profile) => ({
      from: PARTICIPANT_FROM,
      to: [profile.email],
      subject: `¡Hola ${profile.displayName || ""}! Te invitamos a participar en ${festival.name}`,
      html: await render(FestivalActivationEmailTemplate({ profile, festival })),
      tags: [
        { name: "category", value: "festival_activation_invitation" },
        { name: "festival_id", value: String(festival.id) },
      ],
    })),
  );
}

/**
 * How many people a mailing would reach, without sending anything. The
 * confirmation dialog shows it so nobody mails thousands of people by
 * accident, and so an empty audience is visible before the switch flips.
 */
export async function fetchInvitationAudience(
  festivalId: number,
  kind: InvitationKind,
): Promise<InvitationAudienceResult> {
  const actor = await requireAdminOrFestivalAdmin();
  if (!actor) return { success: false, message: "No autorizado" };
  if (
    !FestivalIdSchema.safeParse(festivalId).success ||
    !KindSchema.safeParse(kind).success
  ) {
    return { success: false, message: "Solicitud inválida" };
  }

  try {
    if (kind === "visitor_registration") {
      // Addresses are read rather than counted in SQL so the dialog's numbers
      // come from the same validation the send applies.
      const rows = await db
        .select({
          email: visitors.email,
          registered: sql<boolean>`exists (${hasTicketForFestival(festivalId)})`,
        })
        .from(visitors);
      const audience = { recipients: 0, alreadyRegistered: 0, invalidEmails: 0 };
      for (const row of rows) {
        if (row.registered) audience.alreadyRegistered += 1;
        else if (!isDeliverableEmail(row.email)) audience.invalidEmails += 1;
        else audience.recipients += 1;
      }
      return { success: true, audience };
    }

    const categories = await festivalCategories(festivalId);
    if (categories.length === 0) {
      return {
        success: true,
        audience: { recipients: 0, alreadyRegistered: 0, invalidEmails: 0 },
      };
    }
    const rows = await db
      .select({ email: users.email })
      .from(users)
      .where(invitableParticipant(categories));
    const invalidEmails = rows.filter(
      (row) => !isDeliverableEmail(row.email),
    ).length;
    return {
      success: true,
      audience: {
        recipients: rows.length - invalidEmails,
        alreadyRegistered: 0,
        invalidEmails,
      },
    };
  } catch (error) {
    console.error("Error counting invitation audience", error);
    return {
      success: false,
      message: "No se pudo calcular a quiénes se enviará la invitación.",
    };
  }
}

/**
 * Sends the next pages of a mailing and says where to resume.
 *
 * The browser drives the run one call at a time, because a whole list does
 * not fit in one function invocation: every call re-reads the festival,
 * re-checks permission and picks its recipients itself from the cursor.
 * Nothing about who receives mail is taken from the caller.
 *
 * A page that Resend refuses is reported with its cursor rather than
 * retried here, so the admin sees it and can send that page again; the
 * idempotency key keeps a retry from delivering twice.
 */
export async function sendInvitationBatch(
  input: z.input<typeof BatchInputSchema>,
): Promise<InvitationBatchResult> {
  const actor = await requireAdminOrFestivalAdmin();
  if (!actor) return { success: false, message: "No autorizado" };

  const parsed = BatchInputSchema.safeParse(input);
  if (!parsed.success) {
    return { success: false, message: "Solicitud inválida" };
  }
  const { festivalId, kind, runId, maxPages } = parsed.data;

  try {
    const festival = await loadFestival(festivalId);
    if (!festival) {
      return { success: false, message: "Festival no encontrado" };
    }
    const blocker = sendBlocker(festival, kind);
    if (blocker) return { success: false, message: blocker };

    const categories =
      kind === "participant_activation"
        ? await festivalCategories(festivalId)
        : [];

    let cursor: number | null = parsed.data.cursor;
    let sent = 0;
    let failed = 0;
    let skipped = 0;
    let simulated = false;
    const failures: InvitationPageFailure[] = [];

    for (let page = 0; page < maxPages && cursor !== null; page++) {
      const pageCursor: number = cursor;
      const rows: (VisitorRecipient | BaseProfile)[] =
        kind === "visitor_registration"
          ? await visitorPage(festivalId, pageCursor)
          : await participantPage(categories, pageCursor);

      if (rows.length === 0) {
        cursor = null;
        break;
      }

      cursor =
        rows.length < INVITATION_PAGE_SIZE ? null : rows[rows.length - 1]!.id;

      const { valid, skipped: pageSkipped } = partitionRecipients<Recipient>(
        rows,
      );
      skipped += pageSkipped;
      if (valid.length === 0) continue;

      try {
        const emails =
          kind === "visitor_registration"
            ? await buildVisitorEmails(valid as VisitorRecipient[], festival)
            : await buildParticipantEmails(valid as BaseProfile[], festival);

        const response = await sendBatchEmails(emails, {
          idempotencyKey: invitationIdempotencyKey({
            kind,
            festivalId,
            runId,
            recipientIds: valid.map((recipient) => recipient.id),
          }),
        });
        const { error } = response;
        if ("simulated" in response) simulated = true;

        if (error) {
          console.error("Resend refused an invitation batch", {
            kind,
            festivalId,
            cursor: pageCursor,
            error,
          });
          failed += valid.length;
          failures.push({
            cursor: pageCursor,
            count: valid.length,
            message: error.message,
          });
          continue;
        }
        sent += valid.length;
      } catch (error) {
        console.error("Error sending an invitation batch", {
          kind,
          festivalId,
          cursor: pageCursor,
          error,
        });
        failed += valid.length;
        failures.push({
          cursor: pageCursor,
          count: valid.length,
          message:
            error instanceof Error ? error.message : "Error desconocido",
        });
      }
    }

    return {
      success: true,
      sent,
      failed,
      skipped,
      failures,
      nextCursor: cursor,
      simulated,
    };
  } catch (error) {
    console.error("Error running invitation batch", error);
    return {
      success: false,
      message: "No se pudieron enviar las invitaciones. Inténtalo nuevamente.",
    };
  }
}

const ManualParticipantSendSchema = z.object({
  festivalId: FestivalIdSchema,
  userIds: z
    .array(z.number().int().positive())
    .min(1)
    .max(INVITATION_PAGE_SIZE),
});

/**
 * Re-sends the participant invitation to a hand-picked group, from the
 * "Participantes habilitados" page. The ids only say whom the admin picked:
 * each one must still be a verified participant of one of the festival's
 * categories, read from the database, or it is skipped.
 */
export async function sendParticipantInvitationsToUsers(
  festivalId: number,
  userIds: number[],
): Promise<
  | { success: true; sent: number; skipped: number; message: string }
  | { success: false; message: string }
> {
  const actor = await requireAdminOrFestivalAdmin();
  if (!actor) return { success: false, message: "No autorizado" };

  const parsed = ManualParticipantSendSchema.safeParse({
    festivalId,
    userIds,
  });
  if (!parsed.success) {
    return { success: false, message: "Selecciona entre 1 y 100 personas." };
  }

  try {
    const festival = await loadFestival(parsed.data.festivalId);
    if (!festival) return { success: false, message: "Festival no encontrado" };

    const categories = await festivalCategories(festival.id);
    const ids = [...new Set(parsed.data.userIds)];
    const rows =
      categories.length === 0
        ? []
        : await db
            .select()
            .from(users)
            .where(and(inArray(users.id, ids), invitableParticipant(categories)))
            .orderBy(asc(users.id));
    const { valid } = partitionRecipients(rows);
    const skipped = ids.length - valid.length;
    if (valid.length === 0) {
      return {
        success: false,
        message: "Ninguna de las personas seleccionadas puede recibir la invitación.",
      };
    }

    const { error } = await sendBatchEmails(
      await buildParticipantEmails(valid, festival),
    );
    if (error) {
      console.error("Resend refused a manual invitation batch", error);
      return {
        success: false,
        message: `Resend rechazó el envío: ${error.message}`,
      };
    }

    return {
      success: true,
      sent: valid.length,
      skipped,
      message:
        skipped > 0
          ? `Se enviaron ${valid.length} invitaciones; ${skipped} se omitieron.`
          : `Se enviaron ${valid.length} invitaciones.`,
    };
  } catch (error) {
    console.error("Error sending manual participant invitations", error);
    return {
      success: false,
      message: "No se pudieron enviar las invitaciones. Inténtalo nuevamente.",
    };
  }
}
