"use server";

import { render } from "react-email";
import { and, asc, eq, exists, inArray, sql, type SQL } from "drizzle-orm";
import { z } from "zod";

import type { BaseProfile } from "@/app/api/users/definitions";
import FestivalActivationEmailTemplate from "@/app/emails/festival-activation";
import RegistrationInvitationEmailTemplate from "@/app/emails/registration-invitation";
import { getFestivalSectorAllowedCategories } from "@/app/lib/festival_sectors/helpers";
import type { FestivalWithDates } from "@/app/lib/festivals/definitions";
import {
  INVITATION_KINDS,
  type InvitationAudience,
  type InvitationAudienceResult,
  type InvitationBatchResult,
  type InvitationKind,
  type InvitationPageFailure,
} from "@/app/lib/festivals/invitation-definitions";
import {
  INVITATION_MAX_PAGES_PER_CALL,
  INVITATION_PAGE_SIZE,
  invitationIdempotencyKey,
  isDeliverableEmail,
  partitionRecipients,
  resendOutcome,
  safeGreetingName,
} from "@/app/lib/festivals/invitation-helpers";
import {
  bulkMailExclusion,
  reachableByBulkMail,
} from "@/app/lib/emails/suppressions";
import type { MailingTopic } from "@/app/lib/emails/topics";
import { unsubscribeLinks } from "@/app/lib/emails/unsubscribe-links";
import { requireAdminOrFestivalAdmin } from "@/app/lib/users/helpers";
import { sendBatchEmails } from "@/app/vendors/resend";
import { db } from "@/db";
import {
  festivals,
  festivalSectors,
  profileSubcategories,
  users,
  visitors,
} from "@/db/schema";

const VISITOR_FROM = "Equipo Glitter <equipo@productoraglitter.com>";
const VISITOR_REPLY_TO = "visitantes@productoraglitter.com";
const PARTICIPANT_FROM = "Productora Glitter <eventos@productoraglitter.com>";

/** Which unsubscribe list each mailing honours. */
const INVITATION_TOPICS = {
  visitor_registration: "visitor_invitations",
  participant_activation: "participant_invitations",
} as const satisfies Record<InvitationKind, MailingTopic>;

const FestivalIdSchema = z.number().int().positive();
const KindSchema = z.enum(INVITATION_KINDS);
const BatchInputSchema = z.object({
  festivalId: FestivalIdSchema,
  kind: KindSchema,
  // Generated by the browser once per send run; scopes the idempotency keys.
  runId: z.uuid(),
  cursor: z.number().int().nonnegative(),
  /**
   * Retrying one page: read exactly cursor < id <= throughId, never past it,
   * so recipients who moved into the page's range since are not mailed by
   * a page that was not theirs.
   */
  throughId: z.number().int().positive().nullable().default(null),
  /** Which attempt at this page; part of its idempotency key. */
  attempt: z.number().int().min(0).max(50).default(0),
  maxPages: z
    .number()
    .int()
    .min(1)
    .max(INVITATION_MAX_PAGES_PER_CALL)
    .default(INVITATION_MAX_PAGES_PER_CALL),
});

type VisitorRecipient = { id: number; email: string; firstName: string | null };

async function loadFestival(festivalId: number) {
  const festival = await db.query.festivals.findFirst({
    where: eq(festivals.id, festivalId),
    with: { festivalDates: true },
  });
  if (!festival) return null;
  // The email reads the first and last date; the relation is unordered.
  festival.festivalDates.sort(
    (a, b) => a.startDate.getTime() - b.startDate.getTime(),
  );
  return festival;
}

/**
 * Why `kind` cannot be sent for this festival right now, or null when it can.
 * Every email links to a page that only works while these hold.
 */
function sendBlocker(
  festival: Pick<
    FestivalWithDates,
    "status" | "publicRegistration" | "festivalDates"
  >,
  kind: InvitationKind,
) {
  if (festival.status !== "active") {
    return "Activa el festival antes de enviar invitaciones.";
  }
  if (kind === "visitor_registration") {
    if (!festival.publicRegistration) {
      return "Abre la acreditación antes de invitar a los visitantes.";
    }
    if (festival.festivalDates.length === 0) {
      return "Agrega las fechas del festival antes de invitar a los visitantes.";
    }
  }
  return null;
}

/**
 * The participant categories a festival has stands for: who the activation
 * mail is for. Leaves out the retired `new_artist` and `none`, which no
 * participant can reserve under.
 */
async function festivalCategories(festivalId: number) {
  const sectors = await db.query.festivalSectors.findMany({
    columns: { id: true },
    with: { stands: { columns: { standCategory: true } } },
    where: eq(festivalSectors.festivalId, festivalId),
  });
  return [
    ...new Set(
      sectors.flatMap((sector) => getFestivalSectorAllowedCategories(sector)),
    ),
  ].filter((category) => category !== "none");
}

/**
 * Who can act on the activation mail. Its button opens the festival's terms
 * page, which turns away a profile without subcategories, so mailing one
 * would only send them to an error.
 */
function invitableParticipant(categories: BaseProfile["category"][]) {
  return and(
    eq(users.status, "verified"),
    inArray(users.category, categories),
    exists(
      db
        .select({ one: sql`1` })
        .from(profileSubcategories)
        .where(eq(profileSubcategories.profileId, users.id)),
    ),
  );
}

/**
 * Leaves out participants whose address bounced, who reported us as spam,
 * or who unsubscribed from these announcements. Kept apart from
 * `invitableParticipant` so the count can say why someone was left out.
 */
function reachableParticipant() {
  return reachableByBulkMail(
    sql`${users.email}`,
    INVITATION_TOPICS.participant_activation,
  );
}

/**
 * Visitors are unique by email only as typed, so one person can hold several
 * rows ("Ana@…" and "ana@…"). Both CTEs work on the normalized address: a
 * person is reached once, through their oldest row, and not at all when any
 * of their rows already holds a ticket for this festival.
 */
function visitorAudienceCtes(festivalId: number) {
  return sql`
    with registered as (
      select distinct lower(trim(rv.email)) as email_key
      from visitors rv
      join tickets t on t.visitor_id = rv.id
      where t.festival_id = ${festivalId}
    ),
    canonical as (
      select min(id) as id
      from visitors
      group by lower(trim(email))
    )
  `;
}

/**
 * One page of a mailing: a window of up to a page of candidate ids after
 * `cursor`, and the recipients in it who should get the mail.
 *
 * The window is drawn before anyone is filtered out, so its bounds do not
 * move when someone in it registers or stops qualifying — which the mailing
 * itself makes people do. A retry or a resume therefore reads the same
 * windows, and their idempotency keys still match what may have gone out.
 */
type PageRead<T> = {
  /** Candidates in the window, eligible or not; 0 means the list is done. */
  size: number;
  /** The window's last id. */
  lastId: number;
  recipients: T[];
};

function windowBounds(cursor: number, throughId: number | null, column: SQL) {
  return throughId === null
    ? sql`${column} > ${cursor}`
    : sql`${column} > ${cursor} and ${column} <= ${throughId}`;
}

async function readVisitorPage(
  festivalId: number,
  cursor: number,
  throughId: number | null,
): Promise<PageRead<VisitorRecipient>> {
  const window = await db.execute(sql`
    select min(id) as id
    from visitors
    group by lower(trim(email))
    having ${windowBounds(cursor, throughId, sql`min(id)`)}
    order by 1
    limit ${INVITATION_PAGE_SIZE}
  `);
  const ids = (window.rows as { id: number }[]).map((row) => Number(row.id));
  if (ids.length === 0) return { size: 0, lastId: cursor, recipients: [] };

  const recipients = await db
    .select({
      id: visitors.id,
      email: visitors.email,
      firstName: visitors.firstName,
    })
    .from(visitors)
    .where(
      and(
        inArray(visitors.id, ids),
        sql`lower(trim(${visitors.email})) not in (
          select lower(trim(rv.email))
          from visitors rv
          join tickets t on t.visitor_id = rv.id
          where t.festival_id = ${festivalId}
        )`,
        // Filtered here, never in the window above, so page bounds stay put
        // when someone unsubscribes or bounces mid-run.
        reachableByBulkMail(
          sql`${visitors.email}`,
          INVITATION_TOPICS.visitor_registration,
        ),
      ),
    )
    .orderBy(asc(visitors.id));

  return { size: ids.length, lastId: ids[ids.length - 1]!, recipients };
}

async function readParticipantPage(
  categories: BaseProfile["category"][],
  cursor: number,
  throughId: number | null,
): Promise<PageRead<BaseProfile>> {
  const window = await db
    .select({ id: users.id })
    .from(users)
    .where(windowBounds(cursor, throughId, sql`${users.id}`))
    .orderBy(asc(users.id))
    .limit(INVITATION_PAGE_SIZE);
  const ids = window.map((row) => row.id);
  if (ids.length === 0) return { size: 0, lastId: cursor, recipients: [] };

  const recipients =
    categories.length === 0
      ? []
      : await db
          .select()
          .from(users)
          .where(
            and(
              inArray(users.id, ids),
              invitableParticipant(categories),
              reachableParticipant(),
            ),
          )
          .orderBy(asc(users.id));

  return { size: ids.length, lastId: ids[ids.length - 1]!, recipients };
}

async function buildVisitorEmails(
  recipients: VisitorRecipient[],
  festival: FestivalWithDates,
) {
  return Promise.all(
    recipients.map(async (visitor) => {
      const unsubscribe = unsubscribeLinks(
        { kind: "visitor", id: visitor.id },
        INVITATION_TOPICS.visitor_registration,
      );
      return {
        from: VISITOR_FROM,
        to: [visitor.email],
        replyTo: VISITOR_REPLY_TO,
        subject: `Pre-registro abierto: ${festival.name}`,
        headers: unsubscribe.headers,
        html: await render(
          RegistrationInvitationEmailTemplate({
            festival,
            // Anyone can register a visitor with any name; only a plain name
            // goes into a mail sent from our domain.
            visitorName: safeGreetingName(visitor.firstName),
            unsubscribeUrl: unsubscribe.pageUrl,
          }),
        ),
        tags: [
          { name: "category", value: "festival_registration_invitation" },
          { name: "festival_id", value: String(festival.id) },
        ],
      };
    }),
  );
}

async function buildParticipantEmails(
  recipients: BaseProfile[],
  festival: FestivalWithDates,
) {
  return Promise.all(
    recipients.map(async (profile) => {
      const unsubscribe = unsubscribeLinks(
        { kind: "user", id: profile.id },
        INVITATION_TOPICS.participant_activation,
      );
      return {
        from: PARTICIPANT_FROM,
        to: [profile.email],
        subject: `¡Hola ${profile.displayName || ""}! Te invitamos a participar en ${festival.name}`,
        headers: unsubscribe.headers,
        html: await render(
          FestivalActivationEmailTemplate({
            profile,
            festival,
            unsubscribeUrl: unsubscribe.pageUrl,
          }),
        ),
        tags: [
          { name: "category", value: "festival_activation_invitation" },
          { name: "festival_id", value: String(festival.id) },
        ],
      };
    }),
  );
}

function emptyAudience(): InvitationAudience {
  return {
    recipients: 0,
    alreadyRegistered: 0,
    invalidEmails: 0,
    bounced: 0,
    optedOut: 0,
  };
}

/** Sorts one candidate the way the send would treat them. */
function countReachable(
  audience: InvitationAudience,
  row: { email: string; excluded: "bounced" | "opted_out" | null },
) {
  if (row.excluded === "bounced") audience.bounced += 1;
  else if (row.excluded === "opted_out") audience.optedOut += 1;
  else if (!isDeliverableEmail(row.email)) audience.invalidEmails += 1;
  else audience.recipients += 1;
}

/**
 * How many people a mailing would reach, without sending anything. The
 * confirmation dialog shows it so nobody mails thousands of people by
 * accident, and so an empty audience is visible before the switch flips.
 */
export async function fetchInvitationAudience(
  festivalId: number,
  kind: InvitationKind,
): Promise<InvitationAudienceResult> {
  const actor = await requireAdminOrFestivalAdmin();
  if (!actor) return { success: false, message: "No autorizado" };
  if (
    !FestivalIdSchema.safeParse(festivalId).success ||
    !KindSchema.safeParse(kind).success
  ) {
    return { success: false, message: "Solicitud inválida" };
  }

  try {
    if (kind === "visitor_registration") {
      // Addresses are read rather than counted in SQL so the dialog's numbers
      // come from the same validation the send applies.
      const result = await db.execute(sql`
        ${visitorAudienceCtes(festivalId)}
        select
          v.email,
          lower(trim(v.email)) in (select email_key from registered) as registered,
          ${bulkMailExclusion(sql`v.email`, INVITATION_TOPICS.visitor_registration)} as excluded
        from visitors v
        join canonical c on c.id = v.id
      `);
      const rows = result.rows as {
        email: string;
        registered: boolean;
        excluded: "bounced" | "opted_out" | null;
      }[];
      const audience = emptyAudience();
      for (const row of rows) {
        if (row.registered) audience.alreadyRegistered += 1;
        else countReachable(audience, row);
      }
      return { success: true, audience };
    }

    const categories = await festivalCategories(festivalId);
    if (categories.length === 0) {
      return { success: true, audience: emptyAudience() };
    }
    const rows = await db
      .select({
        email: users.email,
        excluded: bulkMailExclusion(
          sql`${users.email}`,
          INVITATION_TOPICS.participant_activation,
        ),
      })
      .from(users)
      .where(invitableParticipant(categories));
    const audience = emptyAudience();
    for (const row of rows) countReachable(audience, row);
    return { success: true, audience };
  } catch (error) {
    console.error("Error counting invitation audience", error);
    return {
      success: false,
      message: "No se pudo calcular a quiénes se enviará la invitación.",
    };
  }
}

/**
 * Sends the next pages of a mailing and says where to resume.
 *
 * The browser drives the run one call at a time, because a whole list does
 * not fit in one function invocation: every call re-reads the festival,
 * re-checks permission and picks its recipients itself from the cursor.
 * Nothing about who receives mail is taken from the caller.
 *
 * A page that did not go out is reported with its bounds rather than retried
 * here, so the admin sees it and can send exactly that page again.
 */
export async function sendInvitationBatch(
  input: z.input<typeof BatchInputSchema>,
): Promise<InvitationBatchResult> {
  const actor = await requireAdminOrFestivalAdmin();
  if (!actor) return { success: false, message: "No autorizado" };

  const parsed = BatchInputSchema.safeParse(input);
  if (!parsed.success) {
    return { success: false, message: "Solicitud inválida" };
  }
  const { festivalId, kind, runId, throughId, attempt } = parsed.data;
  // A retry is one known page; it never reads on past it.
  const retrying = throughId !== null;
  const maxPages = retrying ? 1 : parsed.data.maxPages;

  try {
    const festival = await loadFestival(festivalId);
    if (!festival) {
      return { success: false, message: "Festival no encontrado" };
    }
    const blocker = sendBlocker(festival, kind);
    if (blocker) return { success: false, message: blocker };

    const categories =
      kind === "participant_activation"
        ? await festivalCategories(festivalId)
        : [];

    let cursor: number | null = parsed.data.cursor;
    let sent = 0;
    let failed = 0;
    let skipped = 0;
    let simulated = false;
    const failures: InvitationPageFailure[] = [];

    for (let page = 0; page < maxPages && cursor !== null; page++) {
      const pageCursor: number = cursor;

      let read: PageRead<VisitorRecipient | BaseProfile>;
      try {
        if (page > 0) {
          // Another admin may have closed acreditación or deactivated the
          // festival since this call began: stop before the next page, and
          // let the next call report why.
          const current = await db.query.festivals.findFirst({
            columns: { status: true, publicRegistration: true },
            where: eq(festivals.id, festivalId),
          });
          if (!current || sendBlocker({ ...festival, ...current }, kind)) {
            break;
          }
        }
        read =
          kind === "visitor_registration"
            ? await readVisitorPage(festivalId, pageCursor, throughId)
            : await readParticipantPage(categories, pageCursor, throughId);
      } catch (error) {
        // Keep what this call already sent; the rest resumes from here.
        console.error("Error reading an invitation page", {
          kind,
          festivalId,
          cursor: pageCursor,
          error,
        });
        failures.push({
          cursor: pageCursor,
          throughId,
          count: 0,
          message: "No se pudo leer la lista de destinatarios.",
          refused: false,
          attempt,
          follow: !retrying,
        });
        cursor = null;
        break;
      }

      if (read.size === 0) {
        cursor = null;
        break;
      }

      // A retry is named by the bounds it was given, so its key matches the
      // attempt it repeats even when the window's last row dropped out.
      const pageThroughId = throughId ?? read.lastId;
      cursor =
        retrying || read.size < INVITATION_PAGE_SIZE ? null : read.lastId;

      const { valid, skipped: pageSkipped } = partitionRecipients(
        read.recipients,
      );
      // A retried page was already counted the first time it was read.
      if (!retrying) skipped += pageSkipped;
      if (valid.length === 0) continue;

      const fail = (message: string, refused: boolean) => {
        failed += valid.length;
        failures.push({
          cursor: pageCursor,
          throughId: pageThroughId,
          count: valid.length,
          message,
          refused,
          attempt,
        });
      };

      try {
        const emails =
          kind === "visitor_registration"
            ? await buildVisitorEmails(valid as VisitorRecipient[], festival)
            : await buildParticipantEmails(valid as BaseProfile[], festival);

        const response = await sendBatchEmails(emails, {
          idempotencyKey: invitationIdempotencyKey({
            kind,
            festivalId,
            runId,
            cursor: pageCursor,
            throughId: pageThroughId,
            attempt,
          }),
        });
        if ("simulated" in response) simulated = true;

        const outcome = resendOutcome(response.error);
        if (outcome === "sent") {
          sent += valid.length;
          continue;
        }
        console.error("Resend did not take an invitation batch", {
          kind,
          festivalId,
          cursor: pageCursor,
          error: response.error,
        });
        fail(
          response.error?.message ?? "Error desconocido",
          outcome === "refused",
        );
      } catch (error) {
        // Our own timeout: Resend may have taken the page, so a retry must
        // reuse this attempt's key to be deduplicated.
        console.error("Error sending an invitation batch", {
          kind,
          festivalId,
          cursor: pageCursor,
          error,
        });
        fail(
          error instanceof Error ? error.message : "Error desconocido",
          false,
        );
      }
    }

    return {
      success: true,
      sent,
      failed,
      skipped,
      failures,
      nextCursor: cursor,
      simulated,
    };
  } catch (error) {
    console.error("Error running invitation batch", error);
    return {
      success: false,
      message: "No se pudieron enviar las invitaciones. Inténtalo nuevamente.",
    };
  }
}

const ManualUserIdsSchema = z
  .array(z.number().int().positive())
  .min(1)
  .max(INVITATION_PAGE_SIZE);

/**
 * Re-sends the participant invitation to a hand-picked group, from the
 * "Participantes habilitados" page. The ids only say whom the admin picked:
 * each one must still be a verified participant of one of the festival's
 * categories, read from the database, or it is skipped.
 */
export async function sendParticipantInvitationsToUsers(
  festivalId: number,
  userIds: number[],
): Promise<
  | { success: true; sent: number; skipped: number; message: string }
  | { success: false; message: string }
> {
  const actor = await requireAdminOrFestivalAdmin();
  if (!actor) return { success: false, message: "No autorizado" };

  if (!FestivalIdSchema.safeParse(festivalId).success) {
    return { success: false, message: "Festival inválido" };
  }
  const parsedIds = ManualUserIdsSchema.safeParse(userIds);
  if (!parsedIds.success) {
    return { success: false, message: "Selecciona entre 1 y 100 personas." };
  }

  try {
    const festival = await loadFestival(festivalId);
    if (!festival) return { success: false, message: "Festival no encontrado" };
    const blocker = sendBlocker(festival, "participant_activation");
    if (blocker) return { success: false, message: blocker };

    const categories = await festivalCategories(festival.id);
    const ids = [...new Set(parsedIds.data)];
    const rows =
      categories.length === 0
        ? []
        : await db
            .select()
            .from(users)
            .where(
              and(
                inArray(users.id, ids),
                invitableParticipant(categories),
                reachableParticipant(),
              ),
            )
            .orderBy(asc(users.id));
    const { valid } = partitionRecipients(rows);
    const skipped = ids.length - valid.length;
    if (valid.length === 0) {
      return {
        success: false,
        message:
          "Ninguna de las personas seleccionadas puede recibir la invitación.",
      };
    }

    const response = await sendBatchEmails(
      await buildParticipantEmails(valid, festival),
    );
    if (response.error) {
      console.error("Resend refused a manual invitation batch", response.error);
      return {
        success: false,
        message: `Resend rechazó el envío: ${response.error.message}`,
      };
    }

    const omitted = skipped > 0 ? `; ${skipped} se omitieron` : "";
    return {
      success: true,
      sent: valid.length,
      skipped,
      message:
        "simulated" in response
          ? `Este entorno no es producción: no se envió ningún correo (habrían sido ${valid.length}${omitted}).`
          : `Se enviaron ${valid.length} invitaciones${omitted}.`,
    };
  } catch (error) {
    console.error("Error sending manual participant invitations", error);
    return {
      success: false,
      message: "No se pudieron enviar las invitaciones. Inténtalo nuevamente.",
    };
  }
}
