export enum ErrorCodes {
	DB_CONNECTION_ERROR = "DB_CONNECTION_ERROR",
	USER_NOT_FOUND = "USER_NOT_FOUND",
	RESERVATION_ALREADY_EXISTS = "RESERVATION_ALREADY_EXISTS",
	NO_PERMISSIONS = "NO_PERMISSIONS",
	USER_HAS_SANCTIONS = "USER_HAS_SANCTIONS",
}
